name: Build and Deploy to Netlify

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - _quarto.yml
      - "!README.md"
  pull_request:
    paths:
      - "**.md"
      - _quarto.yml
      - "!README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          version: "1.0.8"
      - name: Build
        run: quarto render

      - name: Deploy preview to Netlify
        if: ${{ github.event_name == 'pull_request' }}
        uses: nwtgck/actions-netlify@v1
        with:
          production-deploy: false
          production-branch: master
          publish-dir: ./docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-${{ github.event.number }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: Deploy to Netlify
        if: ${{ github.ref == 'refs/heads/master'}}
        uses: nwtgck/actions-netlify@v1
        with:
          production-deploy: true
          production-branch: master
          publish-dir: ./docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
